[package]
name = "strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
# Misc
hashbrown = "0.14.0"
tokio = { version = "1.29.0", features = ["full"] }
dashmap = "5.4.0"
thiserror = "1.0.37"
futures = "0.3.5"
async-trait = "0.1.64"
anyhow = "1.0.70"
serde = "1.0.145"
toml = "0.5"
lazy_static = "1.4"
async_once = "0.2.6"
once_cell = "1.18.0"
uuid = {version = "1.4.1", features = ["v4"]}
hex = "0.4.3"

# EVM based crates
cfmms = { git = "https://github.com/mouseless-eth/cfmms-rs.git", branch = "fix-serialize-dex-fee"}
ethers-flashbots = { git = "https://github.com/onbjerg/ethers-flashbots"}
ethers = {version = "2.0.7", features = ["abigen", "ws"]}
foundry-evm = { git = "https://github.com/mouseless-eth/foundry.git", branch = "ethers-version-change" }
anvil = { git = "https://github.com/mouseless-eth/foundry.git", branch = "ethers-version-change" }
eth-encode-packed = "0.1.0"

# Logging
colored = "2.0.0"
log = "0.4.17"
indicatif = "0.17.5"

chrono = "0.4.23"

# Artemis
artemis-core = { path = "../artemis-core" }

[dev-dependencies]
fern = {version = "0.6.2", features = ["colored"]}

[features]
debug = []
